services:
  desenvolvimento_app:
    image: php:latest
    container_name: desenvolvimento_app
    command: sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && php -S 0.0.0.0:8000"
    working_dir: /app
    ports:
      - 8020:8000
    volumes:
      - ./desenvolvimento:/app

  desenvolvimento_db:
    image: postgres:latest
    container_name: desenvolvimento_db
    environment:
      POSTGRES_DB: desenvolvimento_db
      POSTGRES_USER: desenvolvimento_user
      POSTGRES_PASSWORD: desenvolvimento_password
    volumes:
      - postgres-desenvolvimento-data:/var/lib/postgresql/data
    ports:
      - 5420:5432

  qualidade_app:
    image: php:latest
    container_name: qualidade_app
    command: sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && php -S 0.0.0.0:8000"
    working_dir: /app
    ports:
      - 8021:8000
    volumes:
      - ./qualidade:/app

  qualidade_db:
    image: postgres:latest
    container_name: qualidade_db
    environment:
      POSTGRES_DB: qualidade_db
      POSTGRES_USER: qualidade_user
      POSTGRES_PASSWORD: qualidade_password
    volumes:
      - postgres-qualidade-data:/var/lib/postgresql/data
    ports:
      - 5421:5432

  producao_app:
    image: php:latest
    container_name: producao_app
    command: sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && php -S 0.0.0.0:8000"
    working_dir: /app
    ports:
      - 8022:8000
    volumes:
      - ./producao:/app

  producao_db:
    image: postgres:latest
    container_name: producao_db
    environment:
      POSTGRES_DB: producao_db
      POSTGRES_USER: producao_user
      POSTGRES_PASSWORD: producao_password
    volumes:
      - postgres-producao-data:/var/lib/postgresql/data
    ports:
      - 5422:5432

volumes:
  postgres-desenvolvimento-data:
  postgres-qualidade-data:
  postgres-producao-data: